import { SportsEvent } from '../types';

const today = new Date();

function eventTime(hoursFromNow: number): string {
  const d = new Date(today.getTime() + hoursFromNow * 3600 * 1000);
  return d.toISOString();
}

export const MOCK_SPORTS_EVENTS: SportsEvent[] = [
  {
    id: 'se1',
    homeTeam: 'New York Knicks',
    awayTeam: 'Boston Celtics',
    sport: 'Basketball',
    league: 'NBA',
    venue: 'Madison Square Garden',
    address: '4 Pennsylvania Plaza, New York, NY',
    neighborhood: 'Midtown',
    datetime: eventTime(5),
    distanceMiles: 0.9,
    minPrice: 68,
    ticketUrl: 'https://www.stubhub.com',
    platform: 'stubhub',
  },
  {
    id: 'se2',
    homeTeam: 'New York Rangers',
    awayTeam: 'Tampa Bay Lightning',
    sport: 'Hockey',
    league: 'NHL',
    venue: 'Madison Square Garden',
    address: '4 Pennsylvania Plaza, New York, NY',
    neighborhood: 'Midtown',
    datetime: eventTime(28),
    distanceMiles: 0.9,
    minPrice: 54,
    ticketUrl: 'https://www.ticketmaster.com',
    platform: 'ticketmaster',
  },
  {
    id: 'se3',
    homeTeam: 'New York Yankees',
    awayTeam: 'Boston Red Sox',
    sport: 'Baseball',
    league: 'MLB',
    venue: 'Yankee Stadium',
    address: '1 E 161 St, Bronx, NY',
    neighborhood: 'The Bronx',
    datetime: eventTime(31),
    distanceMiles: 7.2,
    minPrice: 32,
    ticketUrl: 'https://www.stubhub.com',
    platform: 'stubhub',
  },
  {
    id: 'se4',
    homeTeam: 'Brooklyn Nets',
    awayTeam: 'Miami Heat',
    sport: 'Basketball',
    league: 'NBA',
    venue: 'Barclays Center',
    address: '620 Atlantic Ave, Brooklyn, NY',
    neighborhood: 'Downtown Brooklyn',
    datetime: eventTime(52),
    distanceMiles: 3.8,
    minPrice: 44,
    ticketUrl: 'https://www.ticketmaster.com',
    platform: 'ticketmaster',
  },
  {
    id: 'se5',
    homeTeam: 'New York Mets',
    awayTeam: 'Philadelphia Phillies',
    sport: 'Baseball',
    league: 'MLB',
    venue: 'Citi Field',
    address: '41 Seaver Way, Queens, NY',
    neighborhood: 'Flushing, Queens',
    datetime: eventTime(54),
    distanceMiles: 9.1,
    minPrice: 28,
    ticketUrl: 'https://www.stubhub.com',
    platform: 'stubhub',
  },
  {
    id: 'se6',
    homeTeam: 'New York City FC',
    awayTeam: 'Atlanta United',
    sport: 'Soccer',
    league: 'MLS',
    venue: 'Yankee Stadium',
    address: '1 E 161 St, Bronx, NY',
    neighborhood: 'The Bronx',
    datetime: eventTime(78),
    distanceMiles: 7.2,
    minPrice: 22,
    ticketUrl: 'https://www.ticketmaster.com',
    platform: 'ticketmaster',
  },
  {
    id: 'lm1',
    homeTeam: 'LCD Soundsystem',
    awayTeam: '',
    sport: 'Live Music',
    league: 'Concert',
    venue: 'Brooklyn Steel',
    address: '319 Frost St, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    datetime: eventTime(6),
    distanceMiles: 3.2,
    minPrice: 45,
    ticketUrl: 'https://www.ticketmaster.com',
    platform: 'ticketmaster',
  },
  {
    id: 'lm2',
    homeTeam: 'Vampire Weekend',
    awayTeam: '',
    sport: 'Live Music',
    league: 'Concert',
    venue: 'Barclays Center',
    address: '620 Atlantic Ave, Brooklyn, NY',
    neighborhood: 'Downtown Brooklyn',
    datetime: eventTime(30),
    distanceMiles: 3.8,
    minPrice: 55,
    ticketUrl: 'https://www.stubhub.com',
    platform: 'stubhub',
  },
  {
    id: 'lm3',
    homeTeam: 'Jungle',
    awayTeam: '',
    sport: 'Live Music',
    league: 'Concert',
    venue: 'Elsewhere',
    address: '599 Johnson Ave, Brooklyn, NY',
    neighborhood: 'Bushwick',
    datetime: eventTime(8),
    distanceMiles: 4.1,
    minPrice: 30,
    ticketUrl: 'https://www.ticketmaster.com',
    platform: 'ticketmaster',
  },
];

export async function fetchSportsEvents(
  _lat: number,
  _lon: number,
  radiusMiles: number
): Promise<SportsEvent[]> {
  await new Promise(r => setTimeout(r, 600));
  return MOCK_SPORTS_EVENTS.filter(e => e.distanceMiles <= radiusMiles + 3);
}
