import axios from 'axios';
import { Venue, WhimParams, ActivityType } from '../types';

const GOOGLE_API_KEY = process.env.EXPO_PUBLIC_GOOGLE_PLACES_API_KEY || '';

const ACTIVITY_QUERY_MAP: Record<ActivityType, string> = {
  drinks: 'bar cocktail lounge',
  dinner: 'restaurant dinner',
  coffee: 'cafe coffee shop',
  activity: 'activity entertainment venue',
  whatever: 'popular venue',
  sports: 'sports stadium arena',
  watch_sports: 'sports bar',
};

export async function searchVenuesByParams(
  params: WhimParams,
  lat: number,
  lon: number
): Promise<Venue[]> {
  if (!GOOGLE_API_KEY) {
    return getMockVenues(params);
  }
  try {
    const radiusMeters = params.radiusMiles * 1609;
    const query = ACTIVITY_QUERY_MAP[params.activityType];
    const url = `https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=${lat},${lon}&radius=${radiusMeters}&keyword=${encodeURIComponent(query)}&key=${GOOGLE_API_KEY}`;
    const response = await axios.get(url);
    return response.data.results.slice(0, 15).map((p: GooglePlace) => mapGooglePlaceToVenue(p, lat, lon, params.activityType));
  } catch {
    return getMockVenues(params);
  }
}

interface GooglePlace {
  place_id: string;
  name: string;
  vicinity: string;
  geometry: { location: { lat: number; lng: number } };
  rating?: number;
  price_level?: number;
  opening_hours?: { open_now: boolean };
  types: string[];
  photos?: { photo_reference: string }[];
}

function mapGooglePlaceToVenue(p: GooglePlace, userLat: number, userLon: number, activityType: ActivityType): Venue {
  const dist = haversineDistance(userLat, userLon, p.geometry.location.lat, p.geometry.location.lng);
  return {
    id: p.place_id,
    name: p.name,
    address: p.vicinity,
    neighborhood: inferNeighborhood(p.vicinity),
    distanceMiles: parseFloat(dist.toFixed(1)),
    rating: p.rating || 4.0,
    priceLevel: (p.price_level as 1 | 2 | 3 | 4) || 2,
    photos: p.photos?.slice(0, 3).map(ph => `https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=${ph.photo_reference}&key=${GOOGLE_API_KEY}`) || [],
    tags: p.types.slice(0, 4),
    isOpenNow: p.opening_hours?.open_now ?? true,
    activityType,
    matchScore: 0,
    matchExplanation: '',
    isAlternative: false,
  };
}

function haversineDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 3958.8;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function inferNeighborhood(vicinity: string): string {
  const neighborhoods = [
    'Lower East Side', 'Williamsburg', 'West Village', 'East Village', 'SoHo',
    'Tribeca', "Hell's Kitchen", 'Chelsea', 'Midtown', 'Upper East Side',
    'Upper West Side', 'Nolita', 'DUMBO', 'Cobble Hill', 'Carroll Gardens',
    'Flatiron', 'Crown Heights', 'Bushwick', 'Park Slope', 'Financial District',
  ];
  for (const n of neighborhoods) {
    if (vicinity.includes(n)) return n;
  }
  return vicinity.split(',')[1]?.trim() || 'Manhattan';
}

// ─── Venue catalog ───────────────────────────────────────────────────────────
// All real NYC venues. Kept here so AI ranking has a rich pool to work with.

const DINNER_VENUES: Venue[] = [
  {
    id: 'v_d1',
    name: 'Via Carota',
    address: '51 Grove St, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 1.0,
    rating: 4.8,
    priceLevel: 3,
    photos: [],
    tags: ['italian', 'classic', 'intimate', 'lively', 'no_reservation'],
    isOpenNow: true,
    availabilityNote: 'No reservations — get there by 6pm or wait',
    bookingUrl: 'https://www.viacarota.com',
    bookingPlatform: 'website',
    activityType: 'dinner',
    matchScore: 97,
    matchExplanation: 'The platonic ideal of a NYC neighborhood restaurant. Rustic Italian, perfect cocktails, always packed for a reason.',
    isAlternative: false,
  },
  {
    id: 'v_d2',
    name: 'Don Angie',
    address: '103 Greenwich Ave, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 1.2,
    rating: 4.7,
    priceLevel: 3,
    photos: [],
    tags: ['italian', 'trendy', 'lively', 'american_italian'],
    isOpenNow: true,
    bookingUrl: 'https://resy.com/cities/ny/don-angie',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 91,
    matchExplanation: 'Creative Italian-American with legendary pinwheel lasagna. Book on Resy or walk in for the bar.',
    isAlternative: false,
  },
  {
    id: 'v_d3',
    name: 'Dame',
    address: '87 MacDougal St, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 1.1,
    rating: 4.6,
    priceLevel: 3,
    photos: [],
    tags: ['seafood', 'intimate', 'trendy', 'wine_bar', 'british'],
    isOpenNow: true,
    availabilityNote: 'Limited seats — book ahead',
    bookingUrl: 'https://resy.com/cities/ny/dame',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 94,
    matchExplanation: 'Tiny, perfect seafood restaurant. One of NYC\'s most exciting spots right now.',
    isAlternative: false,
  },
  {
    id: 'v_d4',
    name: 'Lilia',
    address: '567 Union Ave, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    distanceMiles: 2.4,
    rating: 4.8,
    priceLevel: 3,
    photos: [],
    tags: ['italian', 'pasta', 'upscale', 'trendy', 'date_night'],
    isOpenNow: true,
    availabilityNote: 'Very hard to get — book weeks ahead on Resy',
    bookingUrl: 'https://resy.com/cities/bk/lilia',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 96,
    matchExplanation: 'Mafaldini with pink peppercorns and sheep\'s milk cheese. Worth every minute hunting for a reservation.',
    isAlternative: false,
  },
  {
    id: 'v_d5',
    name: 'Lucali',
    address: '575 Henry St, Brooklyn, NY',
    neighborhood: 'Carroll Gardens',
    distanceMiles: 3.1,
    rating: 4.9,
    priceLevel: 2,
    photos: [],
    tags: ['pizza', 'casual', 'classic', 'date_night', 'hidden_gem'],
    isOpenNow: true,
    availabilityNote: 'BYOB. They don\'t take reservations — arrive at 5pm to put your name in',
    bookingUrl: 'https://www.lucali.com',
    bookingPlatform: 'website',
    activityType: 'dinner',
    matchScore: 93,
    matchExplanation: 'Best pizza in NYC, full stop. BYOB with a 2-hour wait that\'s 100% worth it.',
    isAlternative: false,
  },
  {
    id: 'v_d6',
    name: 'Carbone',
    address: '181 Thompson St, New York, NY',
    neighborhood: 'Greenwich Village',
    distanceMiles: 1.3,
    rating: 4.6,
    priceLevel: 4,
    photos: [],
    tags: ['italian', 'upscale', 'classic', 'trendy', 'date_night'],
    isOpenNow: true,
    availabilityNote: 'Book exactly 30 days ahead at midnight on Resy',
    bookingUrl: 'https://resy.com/cities/ny/carbone',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 88,
    matchExplanation: 'The spicy rigatoni is a cultural landmark at this point. Glam red-sauce scene, worth the splurge.',
    isAlternative: false,
  },
  {
    id: 'v_d7',
    name: "Katz's Delicatessen",
    address: '205 E Houston St, New York, NY',
    neighborhood: 'Lower East Side',
    distanceMiles: 1.4,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['deli', 'classic', 'casual', 'american', 'late_night', 'iconic'],
    isOpenNow: true,
    activityType: 'dinner',
    matchScore: 82,
    matchExplanation: 'Pastrami on rye since 1888. A New York institution — especially right for a casual, no-fuss night.',
    isAlternative: false,
  },
  {
    id: 'v_d8',
    name: 'Uncle Boons',
    address: '7 Spring St, New York, NY',
    neighborhood: 'Nolita',
    distanceMiles: 1.6,
    rating: 4.6,
    priceLevel: 2,
    photos: [],
    tags: ['thai', 'lively', 'trendy', 'casual', 'hidden_gem'],
    isOpenNow: true,
    bookingUrl: 'https://resy.com/cities/ny/uncle-boons',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 87,
    matchExplanation: 'Vibrant, funky Thai in a converted dive bar. Cocktails are great, the food is even better.',
    isAlternative: false,
  },
  {
    id: 'v_d9',
    name: 'Ivan Ramen',
    address: '25 Clinton St, New York, NY',
    neighborhood: 'Lower East Side',
    distanceMiles: 1.5,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['japanese', 'ramen', 'casual', 'intimate', 'noodles'],
    isOpenNow: true,
    bookingUrl: 'https://ivanramen.com',
    bookingPlatform: 'website',
    activityType: 'dinner',
    matchScore: 85,
    matchExplanation: 'Ivan Orkin\'s ramen shop is the real deal — New York-meets-Tokyo in a bowl. Perfect for a cozy night.',
    isAlternative: false,
  },
  {
    id: 'v_d10',
    name: 'Estela',
    address: '47 E Houston St, New York, NY',
    neighborhood: 'Nolita',
    distanceMiles: 1.5,
    rating: 4.7,
    priceLevel: 3,
    photos: [],
    tags: ['mediterranean', 'upscale', 'hidden_gem', 'wine_bar', 'trendy'],
    isOpenNow: true,
    bookingUrl: 'https://resy.com/cities/ny/estela',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 90,
    matchExplanation: 'Inventive Mediterranean small plates, great wine. The burrata with salsa verde is legendary.',
    isAlternative: false,
  },
  {
    id: 'v_d11',
    name: 'Cosme',
    address: '35 E 21st St, New York, NY',
    neighborhood: 'Flatiron',
    distanceMiles: 0.8,
    rating: 4.5,
    priceLevel: 4,
    photos: [],
    tags: ['mexican', 'upscale', 'trendy', 'date_night', 'lively'],
    isOpenNow: true,
    bookingUrl: 'https://resy.com/cities/ny/cosme',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 86,
    matchExplanation: 'Enrique Olvera\'s modern Mexican. Corn husk meringue is a religion. Reserve well ahead.',
    isAlternative: false,
  },
  {
    id: 'v_d12',
    name: 'Balthazar',
    address: '80 Spring St, New York, NY',
    neighborhood: 'SoHo',
    distanceMiles: 1.4,
    rating: 4.4,
    priceLevel: 3,
    photos: [],
    tags: ['french', 'brasserie', 'classic', 'lively', 'upscale'],
    isOpenNow: true,
    bookingUrl: 'https://resy.com/cities/ny/balthazar',
    bookingPlatform: 'resy',
    activityType: 'dinner',
    matchScore: 83,
    matchExplanation: 'The grand NYC brasserie. Steak frites, raw bar, people-watching — effortlessly timeless.',
    isAlternative: false,
  },
  {
    id: 'v_d13',
    name: 'Peter Luger Steak House',
    address: '178 Broadway, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    distanceMiles: 2.3,
    rating: 4.6,
    priceLevel: 4,
    photos: [],
    tags: ['steakhouse', 'classic', 'upscale', 'american', 'cash_only'],
    isOpenNow: true,
    availabilityNote: 'Cash only. Book weeks ahead',
    bookingUrl: 'https://peterluger.com',
    bookingPlatform: 'website',
    activityType: 'dinner',
    matchScore: 84,
    matchExplanation: 'The porterhouse that NYC built its reputation on. Cash only, zero decor, pure beef.',
    isAlternative: false,
  },
  {
    id: 'v_d14',
    name: 'Momofuku Noodle Bar',
    address: '171 1st Ave, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.9,
    rating: 4.4,
    priceLevel: 2,
    photos: [],
    tags: ['japanese', 'noodles', 'casual', 'lively', 'american_asian'],
    isOpenNow: true,
    bookingUrl: 'https://momofuku.com',
    bookingPlatform: 'website',
    activityType: 'dinner',
    matchScore: 80,
    matchExplanation: 'Where it all started for David Chang. Pork buns, ramen, solid cocktails in a buzzy East Village room.',
    isAlternative: false,
  },
  {
    id: 'v_d15',
    name: 'Superiority Burger',
    address: '430 E 9th St, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.9,
    rating: 4.5,
    priceLevel: 1,
    photos: [],
    tags: ['vegetarian', 'casual', 'hidden_gem', 'american', 'cheap_eats'],
    isOpenNow: true,
    activityType: 'dinner',
    matchScore: 78,
    matchExplanation: 'Best vegetarian burger in the city, possibly the country. Tiny, cheap, no fuss, always worth it.',
    isAlternative: true,
    alternativeNote: 'Wildcard if you want something casual and unexpected.',
  },
];

const DRINKS_VENUES: Venue[] = [
  {
    id: 'v_dr1',
    name: 'Westlight',
    address: '111 N 12th St, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    distanceMiles: 1.8,
    rating: 4.5,
    priceLevel: 3,
    photos: [],
    tags: ['rooftop', 'cocktails', 'views', 'outdoor', 'trendy'],
    isOpenNow: true,
    availabilityNote: 'Walk-ins welcome after 8pm',
    bookingUrl: 'https://resy.com/cities/bk/westlight',
    bookingPlatform: 'resy',
    activityType: 'drinks',
    matchScore: 96,
    matchExplanation: 'Rooftop bar with panoramic Manhattan views. Perfect for outdoor drinks on a warm night.',
    isAlternative: false,
  },
  {
    id: 'v_dr2',
    name: 'Employees Only',
    address: '510 Hudson St, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 0.9,
    rating: 4.7,
    priceLevel: 3,
    photos: [],
    tags: ['speakeasy', 'cocktails', 'intimate', 'classic', 'late_night'],
    isOpenNow: true,
    availabilityNote: 'No reservations, walk-in only',
    bookingUrl: 'https://employeesonlynyc.com',
    bookingPlatform: 'website',
    activityType: 'drinks',
    matchScore: 88,
    matchExplanation: 'Legendary speakeasy-style cocktail bar. Buzzy, intimate, and the clairvoyant at the door sets the vibe.',
    isAlternative: false,
  },
  {
    id: 'v_dr3',
    name: 'Death & Co',
    address: '433 E 6th St, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.7,
    rating: 4.7,
    priceLevel: 3,
    photos: [],
    tags: ['cocktails', 'speakeasy', 'intimate', 'upscale', 'classic'],
    isOpenNow: true,
    bookingUrl: 'https://resy.com/cities/ny/death-and-co',
    bookingPlatform: 'resy',
    activityType: 'drinks',
    matchScore: 93,
    matchExplanation: 'The bar that defined the modern cocktail renaissance. Every drink is a serious craft project.',
    isAlternative: false,
  },
  {
    id: 'v_dr4',
    name: 'Attaboy',
    address: '134 Eldridge St, New York, NY',
    neighborhood: 'Lower East Side',
    distanceMiles: 1.3,
    rating: 4.6,
    priceLevel: 3,
    photos: [],
    tags: ['cocktails', 'speakeasy', 'intimate', 'hidden_gem', 'no_menu'],
    isOpenNow: true,
    availabilityNote: 'No menu — tell them what you like',
    activityType: 'drinks',
    matchScore: 91,
    matchExplanation: 'No menu, just describe your mood and they build you something perfect. LES at its absolute best.',
    isAlternative: false,
  },
  {
    id: 'v_dr5',
    name: 'The Dead Rabbit',
    address: '30 Water St, New York, NY',
    neighborhood: 'Financial District',
    distanceMiles: 2.8,
    rating: 4.7,
    priceLevel: 3,
    photos: [],
    tags: ['cocktails', 'classic', 'upscale', 'irish', 'happy_hour'],
    isOpenNow: true,
    bookingUrl: 'https://thedeadrabbitnyc.com',
    bookingPlatform: 'website',
    activityType: 'drinks',
    matchScore: 87,
    matchExplanation: 'Multi-award-winning cocktail bar. Worth the trip downtown — the punch bowls alone are worth it.',
    isAlternative: false,
  },
  {
    id: 'v_dr6',
    name: 'June Wine Bar',
    address: '231 Court St, Brooklyn, NY',
    neighborhood: 'Cobble Hill',
    distanceMiles: 3.0,
    rating: 4.6,
    priceLevel: 2,
    photos: [],
    tags: ['wine_bar', 'intimate', 'casual', 'hidden_gem', 'natural_wine'],
    isOpenNow: true,
    activityType: 'drinks',
    matchScore: 89,
    matchExplanation: 'Laid-back natural wine bar in Cobble Hill. Great pours, perfect for a low-key date or catch-up.',
    isAlternative: false,
  },
  {
    id: 'v_dr7',
    name: 'Bemelmans Bar',
    address: '35 E 76th St, New York, NY',
    neighborhood: 'Upper East Side',
    distanceMiles: 2.3,
    rating: 4.8,
    priceLevel: 4,
    photos: [],
    tags: ['classic', 'upscale', 'piano_bar', 'intimate', 'date_night'],
    isOpenNow: true,
    bookingUrl: 'https://www.thecarlyle.com/bemelmans-bar',
    bookingPlatform: 'website',
    activityType: 'drinks',
    matchScore: 82,
    matchExplanation: 'Old-world NYC glamour with live piano. Feel like you\'re in a Woody Allen film — in the best way.',
    isAlternative: false,
  },
  {
    id: 'v_dr8',
    name: 'The Press Lounge',
    address: '653 11th Ave, New York, NY',
    neighborhood: "Hell's Kitchen",
    distanceMiles: 1.9,
    rating: 4.4,
    priceLevel: 3,
    photos: [],
    tags: ['rooftop', 'outdoor', 'views', 'upscale', 'trendy'],
    isOpenNow: true,
    bookingUrl: 'https://thepresslounge.com',
    bookingPlatform: 'website',
    activityType: 'drinks',
    matchScore: 84,
    matchExplanation: 'Stunning Hudson River views from a sleek rooftop. Best sunset spot in Hell\'s Kitchen.',
    isAlternative: false,
  },
  {
    id: 'v_dr9',
    name: '230 Fifth',
    address: '230 5th Ave, New York, NY',
    neighborhood: 'Midtown',
    distanceMiles: 1.0,
    rating: 4.1,
    priceLevel: 2,
    photos: [],
    tags: ['rooftop', 'outdoor', 'views', 'lively', 'tourist_friendly'],
    isOpenNow: true,
    bookingUrl: 'https://230-fifth.com',
    bookingPlatform: 'website',
    activityType: 'drinks',
    matchScore: 72,
    matchExplanation: 'Massive Empire State views, always packed. More of a scene than a bar but the rooftop is undeniable.',
    isAlternative: true,
    alternativeNote: 'More touristy but the rooftop views are genuinely hard to beat.',
  },
  {
    id: 'v_dr10',
    name: 'Little Branch',
    address: '20 7th Ave S, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 0.8,
    rating: 4.6,
    priceLevel: 3,
    photos: [],
    tags: ['speakeasy', 'intimate', 'jazz', 'cocktails', 'hidden_gem', 'live_music'],
    isOpenNow: true,
    activityType: 'drinks',
    matchScore: 90,
    matchExplanation: 'Underground jazz bar with world-class cocktails. Squeeze downstairs and don\'t tell anyone about it.',
    isAlternative: false,
  },
  {
    id: 'v_dr11',
    name: "Rudy's Bar & Grill",
    address: '627 9th Ave, New York, NY',
    neighborhood: "Hell's Kitchen",
    distanceMiles: 1.7,
    rating: 4.3,
    priceLevel: 1,
    photos: [],
    tags: ['dive_bar', 'casual', 'cheap', 'classic', 'outdoor'],
    isOpenNow: true,
    activityType: 'drinks',
    matchScore: 76,
    matchExplanation: 'NYC\'s oldest dive bar. $3 beers, free hot dogs, a backyard. Absolutely no pretense.',
    isAlternative: false,
  },
  {
    id: 'v_dr12',
    name: "Amor y Amargo",
    address: '443 E 6th St, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.7,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['bitters', 'cocktails', 'intimate', 'hidden_gem', 'low_key'],
    isOpenNow: true,
    activityType: 'drinks',
    matchScore: 85,
    matchExplanation: 'The world\'s only bitters bar. Tiny, nerdy, and exceptional. If you like cocktails, this is your spot.',
    isAlternative: false,
  },
  {
    id: 'v_dr13',
    name: "Loosie's",
    address: '91 S 6th St, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    distanceMiles: 2.0,
    rating: 4.4,
    priceLevel: 2,
    photos: [],
    tags: ['outdoor', 'casual', 'dive_bar', 'Brooklyn', 'lively'],
    isOpenNow: true,
    activityType: 'drinks',
    matchScore: 74,
    matchExplanation: 'Chill outdoor Williamsburg bar. Different vibe than upscale but the outdoor patio is great in warm weather.',
    isAlternative: true,
    alternativeNote: 'More casual — great if you want outdoor and lively.',
  },
];

const COFFEE_VENUES: Venue[] = [
  {
    id: 'v_c1',
    name: 'Abraço',
    address: '86 E 7th St, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.8,
    rating: 4.6,
    priceLevel: 1,
    photos: [],
    tags: ['espresso', 'intimate', 'hidden_gem', 'casual', 'tiny'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 93,
    matchExplanation: 'Tiny East Village espresso counter. The best single-origin coffee in the neighborhood — always worth the squeeze.',
    isAlternative: false,
  },
  {
    id: 'v_c2',
    name: 'Devoción',
    address: '69 Grand St, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    distanceMiles: 2.1,
    rating: 4.7,
    priceLevel: 2,
    photos: [],
    tags: ['coffee', 'trendy', 'aesthetic', 'colombian', 'specialty'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 91,
    matchExplanation: 'Stunning greenhouse space, Colombian single-origin beans. One of the most Instagrammed coffee shops in NYC — and for good reason.',
    isAlternative: false,
  },
  {
    id: 'v_c3',
    name: 'La Colombe',
    address: '270 Lafayette St, New York, NY',
    neighborhood: 'Nolita',
    distanceMiles: 1.4,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['coffee', 'casual', 'spacious', 'draft_latte', 'reliable'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 84,
    matchExplanation: 'Best draft lattes in the city. Spacious Nolita spot, good for working or catching up.',
    isAlternative: false,
  },
  {
    id: 'v_c4',
    name: 'Cha Cha Matcha',
    address: '373 Broadway, New York, NY',
    neighborhood: 'Tribeca',
    distanceMiles: 1.5,
    rating: 4.3,
    priceLevel: 2,
    photos: [],
    tags: ['matcha', 'trendy', 'casual', 'aesthetic', 'tea'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 85,
    matchExplanation: 'Vibey matcha bar with pastel everything. Great for a chill hang if you\'re not a coffee person.',
    isAlternative: false,
  },
  {
    id: 'v_c5',
    name: 'Joe Coffee',
    address: '141 Waverly Pl, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 1.0,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['coffee', 'casual', 'neighborhood', 'reliable'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 80,
    matchExplanation: 'Reliable, quality West Village coffee spot. Great for a low-key afternoon or catching up with someone.',
    isAlternative: false,
  },
  {
    id: 'v_c6',
    name: 'Think Coffee',
    address: '248 Mercer St, New York, NY',
    neighborhood: 'Greenwich Village',
    distanceMiles: 0.8,
    rating: 4.4,
    priceLevel: 1,
    photos: [],
    tags: ['coffee', 'casual', 'cozy', 'local', 'indie'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 79,
    matchExplanation: 'Great third-wave indie coffee shop. Low-key, solid espresso, a neighborhood staple.',
    isAlternative: false,
  },
  {
    id: 'v_c7',
    name: 'Birch Coffee',
    address: '5 E 27th St, New York, NY',
    neighborhood: 'Flatiron',
    distanceMiles: 0.7,
    rating: 4.4,
    priceLevel: 2,
    photos: [],
    tags: ['coffee', 'casual', 'spacious', 'reliable'],
    isOpenNow: true,
    activityType: 'coffee',
    matchScore: 77,
    matchExplanation: 'Solid Flatiron coffee with good seating and a low-key atmosphere. Good call for midday catch-ups.',
    isAlternative: false,
  },
];

const ACTIVITY_VENUES: Venue[] = [
  {
    id: 'v_a1',
    name: 'Brooklyn Boulders',
    address: '25 Jay St, Brooklyn, NY',
    neighborhood: 'DUMBO',
    distanceMiles: 2.1,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['climbing', 'fitness', 'activity', 'fun', 'social'],
    isOpenNow: true,
    bookingUrl: 'https://brooklynboulders.com',
    bookingPlatform: 'website',
    activityType: 'activity',
    matchScore: 92,
    matchExplanation: 'Bouldering gym that\'s actually a fun social spot. Day passes available, no experience needed.',
    isAlternative: false,
  },
  {
    id: 'v_a2',
    name: 'The High Line',
    address: 'Gansevoort St, New York, NY',
    neighborhood: 'Chelsea',
    distanceMiles: 1.3,
    rating: 4.7,
    priceLevel: 1,
    photos: [],
    tags: ['outdoor', 'park', 'walk', 'views', 'free', 'casual'],
    isOpenNow: true,
    activityType: 'activity',
    matchScore: 85,
    matchExplanation: 'Classic NYC elevated park walk. Great for golden hour, pop-up art, people watching.',
    isAlternative: false,
  },
  {
    id: 'v_a3',
    name: 'Brooklyn Bridge Park',
    address: 'Brooklyn Bridge Park, Brooklyn, NY',
    neighborhood: 'DUMBO',
    distanceMiles: 2.4,
    rating: 4.8,
    priceLevel: 1,
    photos: [],
    tags: ['outdoor', 'waterfront', 'views', 'park', 'free', 'scenic'],
    isOpenNow: true,
    activityType: 'activity',
    matchScore: 89,
    matchExplanation: 'Best Manhattan skyline views in the city. Bring drinks and watch the sun go down over the bridge.',
    isAlternative: false,
  },
  {
    id: 'v_a4',
    name: 'Comedy Cellar',
    address: '117 Macdougal St, New York, NY',
    neighborhood: 'Greenwich Village',
    distanceMiles: 1.2,
    rating: 4.7,
    priceLevel: 2,
    photos: [],
    tags: ['comedy', 'live_entertainment', 'classic', 'intimate', 'nightlife'],
    isOpenNow: true,
    availabilityNote: 'Table minimums — order food and drinks',
    bookingUrl: 'https://comedycellar.com',
    bookingPlatform: 'website',
    activityType: 'activity',
    matchScore: 91,
    matchExplanation: 'NYC\'s most legendary comedy club. Surprise drop-ins from major names happen all the time.',
    isAlternative: false,
  },
  {
    id: 'v_a5',
    name: 'Nitehawk Cinema',
    address: '136 Metropolitan Ave, Brooklyn, NY',
    neighborhood: 'Williamsburg',
    distanceMiles: 2.3,
    rating: 4.6,
    priceLevel: 2,
    photos: [],
    tags: ['cinema', 'cocktails', 'casual', 'date_night', 'entertainment'],
    isOpenNow: true,
    bookingUrl: 'https://nitehawkcinema.com',
    bookingPlatform: 'website',
    activityType: 'activity',
    matchScore: 88,
    matchExplanation: 'Dine-in movie theater with cocktails and food delivered to your seat. Perfect date night.',
    isAlternative: false,
  },
  {
    id: 'v_a6',
    name: 'Chelsea Piers',
    address: '62 Chelsea Piers, New York, NY',
    neighborhood: 'Chelsea',
    distanceMiles: 1.6,
    rating: 4.3,
    priceLevel: 2,
    photos: [],
    tags: ['sports', 'bowling', 'activity', 'waterfront', 'large_group'],
    isOpenNow: true,
    bookingUrl: 'https://chelseapiers.com',
    bookingPlatform: 'website',
    activityType: 'activity',
    matchScore: 80,
    matchExplanation: 'Massive sports complex on the Hudson — bowling, batting cages, rock climbing. Good for a big group.',
    isAlternative: false,
  },
  {
    id: 'v_a7',
    name: 'Standard Biergarten',
    address: '848 Washington St, New York, NY',
    neighborhood: 'Meatpacking',
    distanceMiles: 1.1,
    rating: 4.2,
    priceLevel: 2,
    photos: [],
    tags: ['outdoor', 'casual', 'lively', 'beer', 'ping_pong'],
    isOpenNow: true,
    activityType: 'activity',
    matchScore: 78,
    matchExplanation: 'Outdoor ping pong, pretzels, and cold beer under the High Line. Casual and always lively.',
    isAlternative: false,
  },
  {
    id: 'v_a8',
    name: 'Museum of Natural History',
    address: 'Central Park W & 79th St, New York, NY',
    neighborhood: 'Upper West Side',
    distanceMiles: 3.4,
    rating: 4.6,
    priceLevel: 2,
    photos: [],
    tags: ['museum', 'indoor', 'classic', 'casual', 'educational'],
    isOpenNow: true,
    bookingUrl: 'https://amnh.org',
    bookingPlatform: 'website',
    activityType: 'activity',
    matchScore: 74,
    matchExplanation: 'A NYC institution. The dinosaurs alone are worth it, and the planetarium shows are surprisingly great.',
    isAlternative: false,
  },
  {
    id: 'v_a9',
    name: 'Smorgasburg',
    address: 'East River State Park, Williamsburg',
    neighborhood: 'Williamsburg',
    distanceMiles: 2.0,
    rating: 4.5,
    priceLevel: 1,
    photos: [],
    tags: ['outdoor', 'food_market', 'casual', 'lively', 'weekend_only', 'waterfront'],
    isOpenNow: true,
    availabilityNote: 'Saturday only, 11am–6pm, April–October',
    activityType: 'activity',
    matchScore: 83,
    matchExplanation: 'NYC\'s iconic food market with Manhattan views and 100 vendors. Best Saturday afternoon move.',
    isAlternative: false,
  },
];

const WATCH_SPORTS_VENUES: Venue[] = [
  {
    id: 'vsb1',
    name: 'Standings Bar & Grill',
    address: '43 E 7th St, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.7,
    rating: 4.4,
    priceLevel: 2,
    photos: [],
    tags: ['sports_bar', 'game_day', 'lively', 'multiple_screens', 'classic'],
    isOpenNow: true,
    availabilityNote: 'Game days get packed — arrive early',
    bookingUrl: 'https://standingsnyc.com',
    bookingPlatform: 'website',
    activityType: 'watch_sports',
    matchScore: 95,
    matchExplanation: 'Best sports bar in the East Village. Every game on, great wings, actual sports bar energy.',
    isAlternative: false,
  },
  {
    id: 'vsb2',
    name: "Nevada Smith's",
    address: '74 3rd Ave, New York, NY',
    neighborhood: 'East Village',
    distanceMiles: 0.8,
    rating: 4.3,
    priceLevel: 2,
    photos: [],
    tags: ['sports_bar', 'soccer', 'game_day', 'classic', 'international'],
    isOpenNow: true,
    availabilityNote: 'Opens early for overseas games',
    bookingUrl: 'https://nevadasmiths.net',
    bookingPlatform: 'website',
    activityType: 'watch_sports',
    matchScore: 91,
    matchExplanation: "NYC's legendary soccer bar. Every Premier League match, Champions League, World Cup. Electric on big game nights.",
    isAlternative: false,
  },
  {
    id: 'vsb3',
    name: 'American Whiskey',
    address: '247 W 30th St, New York, NY',
    neighborhood: 'Chelsea',
    distanceMiles: 1.4,
    rating: 4.5,
    priceLevel: 2,
    photos: [],
    tags: ['sports_bar', 'whiskey', 'lively', 'big_screens', 'near_msg'],
    isOpenNow: true,
    availabilityNote: 'Reservations available for game days',
    bookingUrl: 'https://americanwhiskeynyc.com',
    bookingPlatform: 'website',
    activityType: 'watch_sports',
    matchScore: 89,
    matchExplanation: 'Massive screens, massive whiskey list. Right near MSG — great for pre/post Knicks or Rangers.',
    isAlternative: false,
  },
  {
    id: 'vsb4',
    name: "Doc Watson's",
    address: '1490 2nd Ave, New York, NY',
    neighborhood: 'Upper East Side',
    distanceMiles: 2.6,
    rating: 4.2,
    priceLevel: 2,
    photos: [],
    tags: ['sports_bar', 'irish_bar', 'classic', 'game_day', 'pub'],
    isOpenNow: true,
    activityType: 'watch_sports',
    matchScore: 84,
    matchExplanation: 'Classic UES sports bar. All the games, good pub food, reliably lively crowd.',
    isAlternative: false,
  },
  {
    id: 'vsb5',
    name: 'Kettle of Fish',
    address: '59 Christopher St, New York, NY',
    neighborhood: 'West Village',
    distanceMiles: 1.1,
    rating: 4.3,
    priceLevel: 1,
    photos: [],
    tags: ['sports_bar', 'dive', 'casual', 'packers', 'football', 'classic'],
    isOpenNow: true,
    activityType: 'watch_sports',
    matchScore: 82,
    matchExplanation: 'Beloved dive bar and unofficial Packers bar of NYC. Chill, unpretentious, great for any game.',
    isAlternative: false,
  },
  {
    id: 'vsb6',
    name: 'The Ainsworth',
    address: '122 W 26th St, New York, NY',
    neighborhood: 'Chelsea',
    distanceMiles: 1.2,
    rating: 4.1,
    priceLevel: 2,
    photos: [],
    tags: ['sports_bar', 'lively', 'upscale_sports_bar', 'big_screens', 'food'],
    isOpenNow: true,
    bookingUrl: 'https://theainsworthnyc.com',
    bookingPlatform: 'website',
    activityType: 'watch_sports',
    matchScore: 80,
    matchExplanation: 'Upscale sports bar with solid food and lots of screens. Good pick if you want to watch with table service.',
    isAlternative: false,
  },
  {
    id: 'vsb7',
    name: 'Smithfield Bar & Grill',
    address: '139 E 27th St, New York, NY',
    neighborhood: 'Flatiron',
    distanceMiles: 0.9,
    rating: 4.0,
    priceLevel: 2,
    photos: [],
    tags: ['sports_bar', 'casual', 'game_day', 'lively'],
    isOpenNow: true,
    activityType: 'watch_sports',
    matchScore: 76,
    matchExplanation: 'Solid Flatiron sports bar — multiple screens, friendly vibe, good wings.',
    isAlternative: false,
  },
];

export function getMockVenues(params: WhimParams): Venue[] {
  let pool: Venue[];

  switch (params.activityType) {
    case 'dinner':
      pool = DINNER_VENUES;
      break;
    case 'drinks':
      pool = DRINKS_VENUES;
      break;
    case 'coffee':
      pool = COFFEE_VENUES;
      break;
    case 'activity':
      pool = ACTIVITY_VENUES;
      break;
    case 'watch_sports':
      pool = WATCH_SPORTS_VENUES;
      break;
    case 'sports':
      // Live events — no mock venue pool (handled by sportsService)
      return [];
    case 'whatever':
      pool = [
        ...DINNER_VENUES.slice(0, 4),
        ...DRINKS_VENUES.slice(0, 4),
        ...ACTIVITY_VENUES.slice(0, 3),
      ];
      break;
    default:
      pool = DINNER_VENUES;
  }

  // Soft-filter by cuisine preference if provided — keep full pool but boost matches via initial sort
  if (params.cuisine && params.activityType === 'dinner') {
    const cuisine = params.cuisine;
    pool = [
      ...pool.filter(v => v.tags.some(t => t === cuisine || t.includes(cuisine))),
      ...pool.filter(v => !v.tags.some(t => t === cuisine || t.includes(cuisine))),
    ];
  }

  // Soft-filter by bar type if provided
  if (params.barType && params.activityType === 'drinks') {
    const barType = params.barType.replace('_bar', '').replace('_', '_');
    pool = [
      ...pool.filter(v => v.tags.some(t => t.includes(barType) || t === params.barType)),
      ...pool.filter(v => !v.tags.some(t => t.includes(barType) || t === params.barType)),
    ];
  }

  return pool.sort((a, b) => b.matchScore - a.matchScore);
}
